add_newline = false

format = """
$username\
$hostname\
$directory\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold dimmed white"

